### ISSUE TITLE
When indexing files, exceptions occur.

### ISSUE THREAD

**Issue by qwefgh90** [qwefgh90/handyfinder#7]
14:25:40 io.github.qwefgh90.handyfinder.lucene.LuceneHandler [WARN][835] - java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot commit
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2793)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2989)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2956)
	at io.github.qwefgh90.handyfinder.lucene.LuceneHandler.index(LuceneHandler.java:919)
	at io.github.qwefgh90.handyfinder.lucene.LuceneHandler.indexFile(LuceneHandler.java:824)
	at io.github.qwefgh90.handyfinder.lucene.LuceneHandler$1.lambda$0(LuceneHandler.java:749)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by qwefgh90** [comment]
https://github.com/qwefgh90/handyfinder/tree/feature/HeapMemoryChecker

It was solved.

**Comment by qwefgh90** [comment]
FunctionalLatch can check heap memory and works well. But It can't stop other threads from leave critical area before one thread allocates memory.
